name: wine-ml
channels:
  - conda-forge
dependencies:
  - python=3.11
  - flask
  - scikit-learn
  - pandas
  - numpy
  - selenium
  - bs4
  - pytest
  - jupyter
  - pip
  - pip:
    - webdriver-manager